version: "3.9"

services:
  db:
    image: postgres:16
    container_name: revengequeues_db
    environment:
      POSTGRES_DB: revengequeues
      POSTGRES_USER: revengequeues
      POSTGRES_PASSWORD: revengequeues
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
